security:
    # ...
    firewalls:
        main:
            # ...
            logout:
                path: app_logout
                target: app_home  # ou une autre route vers laquelle rediriger après déconnexion
