version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rouedelafortune
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  # Les scripts SQL seront exécutés automatiquement au premier démarrage
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Interface phpMyAdmin pour gérer la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  # Application frontend (Rouedelafortune)
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8888:3000"  # 3000 est le port par défaut de Nuxt.js
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules/
    environment:
      # Configuration pour l'accès direct à MySQL
      DATABASE_URL: mysql://user:password@mysql:3306/rouedelafortune
      # Désactiver le mode mock
      MOCK_MODE: "false"
      USE_MYSQL: "true"
      NODE_ENV: development

volumes:
  mysql-data:
