version: '3'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: rouedelafortune-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rouedelafortune
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rouedelafortune

  # Application Laravel (Rouedelafortune)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rouedelafortune-app
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: rouedelafortune
      DB_USERNAME: user
      DB_PASSWORD: password
      APP_ENV: development
      APP_DEBUG: 'true'
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - rouedelafortune

  # Serveur web Nginx
  nginx:
    image: nginx:alpine
    container_name: rouedelafortune-nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - rouedelafortune

  # Interface phpMyAdmin pour gérer la base de données
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rouedelafortune-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - rouedelafortune

networks:
  rouedelafortune:
    driver: bridge

volumes:
  mysql-data:
