version: '3.8'

services:
  # Base de données PostgreSQL pour Supabase
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./supabase-local/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Application d'initialisation (exécute les migrations au premier lancement uniquement)
  db-init:
    build:
      context: ./db-init
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./supabase-local/migrations:/migrations
      - db-init-data:/init-data

  # Application frontend (Rouedelafortune)
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8888:3000"  # 3000 est le port par défaut de Nuxt.js
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules/
    environment:
      SUPABASE_URL: http://postgres:5432
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY2FsaG9zdCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjE2OTYwMDAwLCJleHAiOjQ3NzA1NjAwMDB9.lbGII8LrENJZpYpsSKdW817FpeWx-8KmgXYy1xtA61Q
      NODE_ENV: development

volumes:
  postgres-data:
  db-init-data:  # Volume pour stocker l'état de l'initialisation
