version: '3'
services:
  postgres:
    image: supabase/postgres:15.1.0.54
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  studio:
    image: supabase/studio:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      SUPABASE_URL: http://api:8000
      STUDIO_PG_META_URL: http://postgres-meta:8080
      POSTGRES_PASSWORD: postgres

  api:
    image: supabase/gotrue:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DB_PASSWORD: postgres
      API_EXTERNAL_URL: http://localhost:8000
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_HOST: postgres
      GOTRUE_DB_PORT: 5432
      GOTRUE_DB_USER: postgres
      GOTRUE_DB_PASSWORD: postgres
      GOTRUE_DB_DATABASE: postgres
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters
      GOTRUE_JWT_EXP: 3600

  postgres-meta:
    image: supabase/postgres-meta:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      PG_META_DB_HOST: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: postgres
      PG_META_DB_NAME: postgres
      PG_META_DB_PORT: 5432

volumes:
  postgres-data:
